### ISSUE TITLE
Clean Getaway任务对话中的翻译问题

### ISSUE THREAD

**Issue by AlexZheng0319** [GTAIV-Complete-Edition-text/GTAIV#56]
1、“停在东岛城地铁站旁边的公屋社区”中“公屋社区”（原文projects）看起来很别扭，可以改成“公共住宅”，“公寓”等...
2、“喂，这车我能搞得它比积灰还烂。”这句（原文Hey, I could fuck this car up worse than a little dirt.）翻译欠佳，可以改成“信不信我把这车搞得更烂？"

**Comment by BlueNoBaka** [comment]
***
### **关于问题1**

修改情况：不作修改

*Firefly Projects* 在游戏中以全称或 *project(s)* 的形式被多次提及，概念上更适合用"社区"进行称呼，以下是几个例子

> ;0x0DE14221=~z~I wanna get down and dirty, babe. Take my ass to the Firefly Projects.
>
> 0x0DE14221=~z~我想去下贱肮脏的地方，宝贝。带我去Firefly公屋社区。

> ;0xF3B311A5=~s~Go to the ~y~projects~s~ in East Holland.
>
> 0xF3B311A5=~s~前往East Holland的~y~公屋社区。

> ;0x972E5985=~z~I don't pretend that I wouldn't be selling my ass for crack if I was born in project housing though.
>
> 0x972E5985=~z~要是我出生在公屋社区，多半也会为了毒品出卖肉体。
>
> (此处并不是特指 *Firefly Projects*)

> ;0x7D5DF358=~z~Ah, the housing projects of the world's finest city.
>
> 0x7D5DF358=~z~啊，世界第一城市的公屋社区。
>
> (直升机观光中的介绍词)

> ;0x97E1C107=Linked to African American gangs in the Firefly Projects.
>
> 0x97E1C107=与Firefly公屋社区的非裔帮派有联系。
>
> (警方数据库中的条目)

> ;0xA23AED2B=~z~Ray, I've made some noise in these projects. I don't think I'm going to be able to find your boy, Teddy.
>
> 0xA23AED2B=~z~Ray，我在公屋社区闹了点动静，估计是找不到你要的Teddy了。

对于本 issue 中的译文，若改为"公共住宅"，`停在东岛城地铁站旁边的公共住宅` 其实也不太合适，需要再加一个"区"字或"附近""里"，"公寓"同理

跳出这一条字幕，再看一下其他文本中出现的 *projects*，我认为译文中采用"公屋社区"进行称呼是合理的

当然，在合适的地方也可以略作"公屋"，省去"社区"二字

***
### **关于问题2**

修改情况：采用，修改为"喂，信不信我把这车搞得更烂？"
