### ISSUE TITLE
Ivan the Not So Terrible任务对话中的翻译问题

### ISSUE THREAD

**Issue by AlexZheng0319** [GTAIV-Complete-Edition-text/GTAIV#57]
No, I mean underneath it... great... listen, I'll call you back, eh? Sorry.
不是，再往下点...很好...听着，我待会再打过来，啊？不好意思。
“再往下点"应该改成“里面的”，才能让人联想到他是在说里面贴身穿的衣物。

**Comment by BlueNoBaka** [comment]
修改情况：将"再往下点"修改为"再里面点"
