### ISSUE TITLE
Waste Not Want Knots任务对话中的翻译问题

### ISSUE THREAD

**Issue by AlexZheng0319** [GTAIV-Complete-Edition-text/GTAIV#60]
1、
> ;0x1E131313=~z~Only places an honest criminal can make any money are these shit holes.
> 0x1E131313=~z~唯独老实的罪犯能挣到钱的地方还是粪坑。

先撇开意思不谈，这句话是句病句，读不通，“唯独”放在前面像限定“罪犯”一样。意思层面，在群里已讨论过，我个人比较认同“罪犯的生存空间被’主题公园‘侵占了，‘只剩下’粪坑了“这种看法，所以我觉得应该改成”老实的罪犯能挣到钱的地方只有粪坑了“。

2、
> ;0xAF336D60=~z~No one's fucking with me, Niko. This is how things work here.
> 0xAF336D60=~z~没有人敢搞我，Niko。只是这里就是这样。

这里的"只是“可以去掉。

**Comment by BlueNoBaka** [comment]
***
### **关于问题1**

修改情况：修改为"老实的罪犯能挣到钱的地方只剩下这些粪坑了。"

顺便说一下，"唯独"修饰的是"老实的罪犯能挣到钱的**地方**"，而不是"老实的**罪犯**"。只是修饰"地方"的定语太多了，应该不算是语病吧，最多有点不好断句。"唯独北京""唯独那个地方""唯独老实的罪犯能挣到钱的地方"

把最前面的"唯独"换成"只有"其实是等价的，"只有……的地方还是粪坑"。

***
### **关于问题2**

修改情况：暂不修改

如果去掉"只是"，`没有人敢搞我，Niko。这里就是这样。`这两句话出现在同一条字幕中容易把`这里就是这样`误解成对`没有人敢搞我`的强调。所以在后半句开头补了一个"只是"，显得更像是话还没说完，后面接着说的样子。

觉得"只是"二字有点啰嗦的话，也可以换成"但"，需要这么改就说一下，不说就不改了。

**Comment by AlexZheng0319** [comment]
> ***
> ### **关于问题1**
> 
> 修改情况：修改为"老实的罪犯能挣到钱的地方只剩下这些粪坑了。"
> 
> 顺便说一下，"唯独"修饰的是"老实的罪犯能挣到钱的**地方**"，而不是"老实的**罪犯**"。只是修饰"地方"的定语太多了，应该不算是语病吧，最多有点不好断句。"唯独北京""唯独那个地方""唯独老实的罪犯能挣到钱的地方"
> 
> 把最前面的"唯独"换成"只有"其实是等价的，"只有……的地方还是粪坑"。
> 
> ***
> ### **关于问题2**
> 
> 修改情况：暂不修改
> 
> 如果去掉"只是"，`没有人敢搞我，Niko。这里就是这样。`这两句话出现在同一条字幕中容易把`这里就是这样`误解成对`没有人敢搞我`的强调。所以在后半句开头补了一个"只是"，显得更像是话还没说完，后面接着说的样子。
> 
> 觉得"只是"二字有点啰嗦的话，也可以换成"但"，需要这么改就说一下，不说就不改了。

问题1：
换成“只”还有一个理由：“唯独”很少单独出现在一个句子里，而是搭配在一个前后转折中的后一句的开头。“只”在一个单独的句子中表示转折比较常见。

问题2：
那之前是我没理解出这个意思，如果是这样的话那就不用改了。
